<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeskripsiTipologiTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('deskripsi_tipologi')->delete();

        DB::table('deskripsi_tipologi')->insert([
            ['id' => 1,  'kode_tipologi' => 'AMB', 'nama_tipologi' => 'Ambassador',       'deskripsi_kekuatan' => 'Bersahabat, menyampaikan dan menjelaskan sesuatu, senang melayani dan bertanggung jawab', 'deskripsi_kelemahan' => 'Sulit berkata tidak, terlalu fokus pada orang lain, menghindari konflik, mudah lelah karena tanggung jawab berlebih, cenderung perfeksionis dalam membantu orang lain', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 2,  'kode_tipologi' => 'ADM', 'nama_tipologi' => 'Administrator',     'deskripsi_kekuatan' => 'Memiliki pola kerja yang terstruktur, terencana, rapih, suka melayani serta menjunjung tinggi tanggung jawab dan ketaatan tata tertib', 'deskripsi_kelemahan' => 'Kaku terhadap perubahan, kurang fleksibel, mudah stres saat rencana terganggu, sulit mendelegasikan tugas, terlalu menuntut kesempurnaan dari diri sendiri dan orang lain', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 3,  'kode_tipologi' => 'ANA', 'nama_tipologi' => 'Analyst',           'deskripsi_kekuatan' => 'Memiliki ketertarikan dengan hitung-menghitung berhubungan dengan angka, data dan analisis', 'deskripsi_kelemahan' => 'Terlalu fokus pada detail, kurang peka terhadap aspek emosional, cenderung kaku dalam berpikir, sulit melihat gambaran besar, mudah terjebak dalam perhitungan yang rumit', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 4,  'kode_tipologi' => 'ARR', 'nama_tipologi' => 'Arranger',          'deskripsi_kekuatan' => 'Suka mengatur seorang atau sekelompok untuk bekerjasama dalam hal penempatan atau penugasan orang, barang ataupun event', 'deskripsi_kelemahan' => 'Cenderung dominan, sulit menerima masukan, terlalu mengontrol, kurang memberi ruang inisiatif orang lain, mudah frustasi jika tim tidak berjalan sesuai rencana', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 5,  'kode_tipologi' => 'CAR', 'nama_tipologi' => 'Caretaker',         'deskripsi_kekuatan' => 'Memberikan perhatian atau merawat orang lain yang memiliki masalah fisik, mental, medis atau kesejahteraan umum. mampu merasakan perasaan orang lain serta terdorong membantu orang lain', 'deskripsi_kelemahan' => 'Mudah terbawa perasaan, sulit menjaga batasan pribadi, cepat lelah secara emosional, cenderung mengabaikan kebutuhan diri sendiri, rentan merasa bersalah jika tidak bisa membantu', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 6,  'kode_tipologi' => 'CMD', 'nama_tipologi' => 'Commander',         'deskripsi_kekuatan' => 'Memiliki kemampuan mengantur dan mengawasi dalam melaksanakan tugas, tegas, mungkin keras kepala, berani mengambil tanggung jawab', 'deskripsi_kelemahan' => 'Cenderung otoriter, kurang mendengarkan pendapat orang lain, sulit berkompromi, terlalu fokus pada kontrol, bisa terlihat kaku atau kurang empati dalam kepemimpinan', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 7,  'kode_tipologi' => 'COM', 'nama_tipologi' => 'Communicator',      'deskripsi_kekuatan' => 'Mudah dalam mengkomunikasikan sesuatu secara sederhana, menarik dan mudah dimengerti', 'deskripsi_kelemahan' => 'Cenderung menyederhanakan hal yang kompleks, kurang mendalam dalam penyampaian, terlalu fokus pada gaya daripada isi, mudah bosan dengan topik yang terlalu teknis atau detail', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 8,  'kode_tipologi' => 'CRE', 'nama_tipologi' => 'Creator',           'deskripsi_kekuatan' => 'Memiliki imajinasi dalam suatu rancangan, memiliki ide yang muncul secara spontan dan bervariasi', 'deskripsi_kelemahan' => 'Sulit fokus pada satu ide, mudah terdistraksi, kurang terstruktur, sulit merealisasikan ide, cenderung mengabaikan detail teknis atau praktis', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 9,  'kode_tipologi' => 'DES', 'nama_tipologi' => 'Designer',          'deskripsi_kekuatan' => 'Senang membuat gambar atau illustrasi bagunan atau produk yang akan dibuat, memiliki sifat analitis juga memiliki beragam ide kreatif', 'deskripsi_kelemahan' => 'Cenderung terjebak pada detail visual, sulit memilih ide utama, perfeksionis, lambat ambil keputusan, dan kurang kolaboratif', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 10, 'kode_tipologi' => 'DIS', 'nama_tipologi' => 'Distributor',       'deskripsi_kekuatan' => 'Memiliki sifat ulet, teguh dalam beraktivitas pekerjaan mencakup mengirimkan sesuatu berupa barang, surat atau artikel pada saat yang hampir bersamaan', 'deskripsi_kelemahan' => 'Cenderung bekerja berulang tanpa refleksi, mudah lelah secara fisik, kurang fleksibel saat situasi berubah, dan minim inovasi dalam metode', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 11, 'kode_tipologi' => 'EDU', 'nama_tipologi' => 'Educator',          'deskripsi_kekuatan' => 'Mengajar, membimbing, menyampaikan, melatih ilmu dan/atau keterampilan agar bisa dipahami orang lain, selalu ingin memajukan orang lain dan senang melihat kemajuan orang yang dibimbingnya', 'deskripsi_kelemahan' => 'Cenderung terlalu mengontrol, sulit menerima metode belajar berbeda, mudah frustrasi saat perkembangan lambat, dan mengabaikan kebutuhan dirinya sendiri', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 12, 'kode_tipologi' => 'EVA', 'nama_tipologi' => 'Evaluator',         'deskripsi_kekuatan' => 'Mengumpulkan informasi, mempelajari dan menimbang dalam rangka memutuskan sesuatu terkait nilai, mutu, kepentingan atau kondisi', 'deskripsi_kelemahan' => 'Terlalu lama dalam mengambil keputusan, cenderung perfeksionis, sulit menerima ketidakpastian, dan bisa mengabaikan dinamika atau konteks sosial', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 13, 'kode_tipologi' => 'EXP', 'nama_tipologi' => 'Explorer',          'deskripsi_kekuatan' => 'Senang mempelajari latar belakang, senang berolah pikir dan melakukan penelitian untuk menemukan fakta-fakta', 'deskripsi_kelemahan' => 'Terlalu banyak menganalisis, sulit mengambil keputusan cepat, tenggelam dalam detail, cenderung skeptis, kurang responsif terhadap hal yang bersifat praktis atau instan', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 14, 'kode_tipologi' => 'INT', 'nama_tipologi' => 'Interpreter',       'deskripsi_kekuatan' => 'Suka menjelaskan arti atau makna dari sesuatu sehingga mudah dipahami orang lain, senang berkomunikasi baik dalam bentuk tulisan dan lisan', 'deskripsi_kelemahan' => 'Cenderung terlalu banyak bicara, sulit menyampaikan secara singkat, mudah terjebak dalam penjelasan yang berulang, kurang mendengarkan, terlalu fokus pada sudut pandang sendiri', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 15, 'kode_tipologi' => 'JOU', 'nama_tipologi' => 'Journalist',        'deskripsi_kekuatan' => 'Senang mengkomunikasikan idenya, suka mengumpulkan berbagai informasi dengan rapih, terstruktur dan teratur', 'deskripsi_kelemahan' => 'Terlalu terpaku pada struktur, sulit menerima perubahan mendadak, cenderung overthinking saat ide tidak tersampaikan dengan baik, kurang fleksibel dalam menyusun informasi, bisa terjebak dalam perencanaan tanpa eksekusi', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 16, 'kode_tipologi' => 'MAR', 'nama_tipologi' => 'Marketer',          'deskripsi_kekuatan' => 'Senang berpikiran strategis, menyampaikan atau mengkomunikasikan sesuatu, memiliki ide kreatif dan senang menonjolkan kelebihan produk/jasa yang diusungnya', 'deskripsi_kelemahan' => 'Cenderung terlalu fokus pada gambaran besar, kurang memperhatikan detail teknis, bisa terlalu percaya diri, berisiko memaksakan ide, dan mudah kecewa jika ide tidak diterima dengan antusias', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 17, 'kode_tipologi' => 'MED', 'nama_tipologi' => 'Mediator',          'deskripsi_kekuatan' => 'Mampu mengatasi dan menyelesaikan konflik antara dua belah pihak yang berselisih, tegas menghadapi orang dan tidak menyukai konflik', 'deskripsi_kelemahan' => 'Cenderung menghindari konfrontasi langsung, bisa terlihat terlalu mengontrol, sulit bersikap netral sepenuhnya, mudah terbebani secara emosional, dan kurang fleksibel dalam menghadapi dinamika emosi orang lain', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 18, 'kode_tipologi' => 'MOT', 'nama_tipologi' => 'Motivator',         'deskripsi_kekuatan' => 'Senang memberikan semangat kepada individu atau sekelompok agar bisa menjadi lebih baik, melalui gaya dan stylenya sendiri', 'deskripsi_kelemahan' => 'Fokus pada gaya bukan isi, tampak berlebihan, mudah kecewa tanpa respons positif, kurang peka pada kebutuhan gaya berbeda', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 19, 'kode_tipologi' => 'OPE', 'nama_tipologi' => 'Operator',          'deskripsi_kekuatan' => 'Senang menjalankan, mengoperasikan dan merawat mesin, peralatan, proses atau sistem, senang melayani, teratur, disiplin, serta gigih bekerja', 'deskripsi_kelemahan' => 'Kurang fleksibel terhadap perubahan, cenderung monoton, sulit beradaptasi dengan hal baru, terlalu fokus pada prosedur, dan kurang tertarik pada aspek kreatif atau inovatif', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 20, 'kode_tipologi' => 'PRO', 'nama_tipologi' => 'Producer',          'deskripsi_kekuatan' => 'Senang memasang, memproduksi, membangun mesin, perangkat atau bangunan, sosok pekerja keras, teratur dan gerak cepat', 'deskripsi_kelemahan' => 'Kurang sabar saat lambat, abaikan rencana jangka panjang, terburu ambil keputusan, cuek emosi, fokus hasil, lupakan proses', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 21, 'kode_tipologi' => 'QCA', 'nama_tipologi' => 'Quality Controller', 'deskripsi_kekuatan' => 'Suka mengawasi dan memeriksa suatu proses pembuatan produk/jasa sesuai dengan ketentuan kualitas/estetika (SOP), sosok perfeksionis, teliti dan fokus', 'deskripsi_kelemahan' => 'Terlalu perfeksionis, sulit puas dengan hasil, cenderung micromanage, mudah stres jika standar tidak terpenuhi, dan kurang fleksibel terhadap improvisasi atau perubahan mendadak', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 22, 'kode_tipologi' => 'RES', 'nama_tipologi' => 'Restorer',          'deskripsi_kekuatan' => 'Menyukai memperbaiki atau memulihkan sesuatu ke fungsi normalnya atau lebih baik, senang mengutak-atik, mencari tahu sistem kerja dan mengembalikan fungsi sesuatu', 'deskripsi_kelemahan' => 'Terpaku cara lama, sulit menerima kegagalan, mudah frustrasi tanpa solusi, terlalu teknis, abaikan aspek emosional dan sosial', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 23, 'kode_tipologi' => 'SAF', 'nama_tipologi' => 'Safekeeper',        'deskripsi_kekuatan' => 'Memiliki sifat teliti, hati-hati, waspada dan memegang teguh tanggung jawab', 'deskripsi_kelemahan' => 'Lambat ambil keputusan, terlalu khawatir salah, sulit ambil risiko, kurang spontan, overthinking saat menghadapi tugas', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 24, 'kode_tipologi' => 'SEL', 'nama_tipologi' => 'Seller',            'deskripsi_kekuatan' => 'Umumnya menyukai berhubungan dengan orang lain, baik untuk mempengaruhi, bekerjasama atau melayani', 'deskripsi_kelemahan' => 'Mudah terpengaruh oleh opini orang lain, sulit bekerja sendiri, cenderung menghindari konflik demi menjaga hubungan, terlalu fokus menyenangkan orang lain, dan rentan kelelahan sosial', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 25, 'kode_tipologi' => 'SER', 'nama_tipologi' => 'Server',            'deskripsi_kekuatan' => 'Memiliki sifat yang tulus dalam bekerja dan melayani orang lain, suka melayani orang lain dan mendahulukan kepentingan orang lain', 'deskripsi_kelemahan' => 'Cenderung mengabaikan kebutuhan diri sendiri, mudah dimanfaatkan, sulit mengatakan tidak, cepat merasa bersalah, dan rentan kelelahan emosional karena terlalu banyak memberi', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 26, 'kode_tipologi' => 'SLC', 'nama_tipologi' => 'Selector',          'deskripsi_kekuatan' => 'Memiliki kemampuan untuk memilih dan merekrut seseorang sesuai dengan apa yang dibutuhkan, memiliki insting kuat dalam melihat keunikan sifat orang lain sehingga dapat memperkirakan potensinya', 'deskripsi_kelemahan' => 'Menilai pakai intuisi tanpa data, bias kesan pertama, terlalu percaya diri, sulit objektif, rawan salah menempatkan orang', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
            ['id' => 27, 'kode_tipologi' => 'STR', 'nama_tipologi' => 'Strategist',        'deskripsi_kekuatan' => 'Memiliki kemampuan perencanaan yang baik untuk mencapai goals, memiliki insting kuat dalam memilih solusi yang tepat, bijaksana dan penuh pertimbangan', 'deskripsi_kelemahan' => 'Cenderung overthinking, terlalu lama dalam mengambil keputusan, sulit bersikap spontan, terlalu banyak mempertimbangkan risiko, dan bisa kurang fleksibel dalam situasi mendesak', 'created_at' => '2025-08-20 06:19:14', 'updated_at' => '2025-08-20 06:19:14'],
        ]);
    }
}
